tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.logger
                - tactician.middleware.locking
                - tactician.middleware.command_handler
